### PR TITLE
Heatmaps

### PR DESCRIPTION
**Pull request by CcAaQq**

### CODE REVIEW

**Comment by Lmamaril** [comment]
This is a great start! I have a couple requests before pushing this into main:

[] I've tried loading this and it has taken about a minute to load. Is there anything we can do in the code to lower the latency we're getting?
[] Rather than putting the classification number of the label on the square, Anqi, could you try putting the date instead? (ie. 3/22/21) . This would remove redundancy and the user could use the colors in the legend for classification. If done, then it'd be best to remove the titles in the  y-axis

**Comment by Lmamaril** [comment]
When I did look at the latency it was only a slow load for the heatmaps (not for stacked bar or pie chart)

**Comment by CcAaQq** [comment]
> This is a great start! I have a couple requests before pushing this into main:
> 
> [] I've tried loading this and it has taken about a minute to load. Is there anything we can do in the code to lower the latency we're getting?
> [] Rather than putting the classification number of the label on the square, Anqi, could you try putting the date instead? (ie. 3/22/21) . This would remove redundancy and the user could use the colors in the legend for classification. If done, then it'd be best to remove the titles in the y-axis

For the latency, I'm not familiar with the async functions in Javascript. Could anyone who's fluent in Javascript help with that? For putting the date on the square, I couldn't do that with the current framework, I'll look at other heat map frameworks.

**Comment by Lmamaril** [comment]
@CcAaQq I'm wondering if the latency issue is being caused by DataAdaptor() being called 8 times for the two heatmaps. I am looking into this more at the moment. There could be other causes.

**Comment by huizhifan** [comment]
> @CcAaQq I'm wondering if the latency issue is being caused by DataAdaptor() being called 8 times for the two heatmaps. I am looking into this more at the moment. There could be other causes.

You are right Leah. The DataAdaptor is called more than we need now. I was doing this for Piechart and Stackbar to finish the components before the demo. I will fix it later this week and see if it helps with the latency.

**Comment by CcAaQq** [comment]
> > @CcAaQq I'm wondering if the latency issue is being caused by DataAdaptor() being called 8 times for the two heatmaps. I am looking into this more at the moment. There could be other causes.
> 
> You are right Leah. The DataAdaptor is called more than we need now. I was doing this for Piechart and Stackbar to finish the components before the demo. I will fix it later this week and see if it helps with the latency.



> @CcAaQq I'm wondering if the latency issue is being caused by DataAdaptor() being called 8 times for the two heatmaps. I am looking into this more at the moment. There could be other causes.

I'll learn about and try to fix the issue this week as well.

**Pull request merged**
